export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="minimal"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git python tmuxinator tmux osx zsh-syntax-highlighting)




source $ZSH/oh-my-zsh.sh

# User configuration

export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH="$HOME/Library/Haskell/bin:$PATH"
export PATH="$HOME/.scripts/:$PATH"

path+=("/Applications/ghc-7.10.0.20150123")

alias wtc="git commit -m $(curl -s http://whatthecommit.com/index.txt)"

function gitshort {
    curl -i -s http://git.io -F "url=$1" | awk '/git.io/{print $2}' | pbcopy
}

alias sprunge="curl -s -F 'sprunge=<-' http://sprunge.us | pbcopy"
source /usr/local/bin/virtualenvwrapper.sh
source ~/.nvm/nvm.sh

#if which tmux 2>&1 >/dev/null; then
#    if [ $TERM != "screen-256color" ] && [ $TERM != "screen" ]; then
#        tmux attach -t misc || tmux new -s misc; exit
#    fi
#fi

export NVM_DIR="/Users/broby/.nvm"

export GOPATH=$HOME/Google\ Drive/Programmering/Go
export PATH=$PATH:$GOPATH/bin
export GOROOT=/usr/local/go
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

export ALTERNATE_EDITOR=""
export EDITOR=vim

export GHC_DOT_APP="/Applications/ghc-7.8.4.app"

if [ -d "$GHC_DOT_APP" ]; then
    export PATH="${HOME}/.cabal/bin:${GHC_DOT_APP}/Contents/bin:${PATH}"
fi

alias mux=tmuxinator
alias vim=nvim
source ~/.bin/tmuxinator.zsh

bindkey -v
